---
- name: Ensure group "admin" exists
  group:
    name: admin
    state: present

- name: "Allow admin users to sudo without a password"
  lineinfile:
    dest: "/etc/sudoers"
    state: "present"
    regexp: "^%admin"
    line: "%admin ALL=(ALL) NOPASSWD: ALL"

- name: "Create user accounts {{ ssh_username }}"
  user:
    name: "{{ ssh_username }}"
    shell: "/bin/bash"
    groups: "admin"

- name: "Add authorized keys"
  authorized_key:
    user: "{{ ssh_username }}"
    key: "{{ ssh_publickey }}"
